--G.w.

-- <IditG>, <IditG MP dbchanges - add message MP1002 to GLST_SGIA_MISHNI for 5.28.08>, <01/01/2012>
INSERT INTO GLST_SGIA_MISHNI (GL_ZIHUY_HODAA,GL_HODAA,GL_MIVNE_HALON_HODAA,GL_HUMRA_HODAA,GL_KOD_TIPUL)
VALUES('MP1002','פרעון שביום האחרון בחודש יש לסמן "סוף חודש"','MT','W','D');
COMMIT;

-- RuslanY - SQ DB changes for 5.28.08, 02/01/2012
DROP TABLE SQST_SUG_CHATACH;

CREATE TABLE SQST_SUG_CHATACH ( SQ_SUG_CHATACH VARCHAR(3) NOT NULL,
								GL_TEUR VARCHAR(20) NOT NULL,
								SQ_SW_HOVA_SCHUM VARCHAR(1) NOT NULL,
								SQ_SW_SHBD_NOCH_REMO VARCHAR(1) NOT NULL,
								SQ_SW_SHBD_ATIDI_ADD VARCHAR(1) NOT NULL,
								SQ_SW_SHBD_ATIDI_REM VARCHAR(1) NOT NULL,
								SQ_SW_SHBD_ALL_ADD VARCHAR(1) NOT NULL,
								SQ_SW_SHBD_ALL_REMOV VARCHAR(1) NOT NULL
							   );
ALTER TABLE SQST_SUG_CHATACH
ADD CONSTRAINT SQST_SUG_CHATACH PRIMARY KEY ("SQ_SUG_CHATACH");
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SQST_SUG_CHATACH TO USER MATAFAPP;

INSERT INTO SQST_SUG_CHATACH (SQ_SUG_CHATACH,GL_TEUR,SQ_SW_HOVA_SCHUM,SQ_SW_SHBD_NOCH_REMO,SQ_SW_SHBD_ATIDI_ADD,SQ_SW_SHBD_ATIDI_REM,SQ_SW_SHBD_ALL_ADD,SQ_SW_SHBD_ALL_REMOV) VALUES ('1','לפי הכל','0','1','1','1','1','1');
INSERT INTO SQST_SUG_CHATACH (SQ_SUG_CHATACH,GL_TEUR,SQ_SW_HOVA_SCHUM,SQ_SW_SHBD_NOCH_REMO,SQ_SW_SHBD_ATIDI_ADD,SQ_SW_SHBD_ATIDI_REM,SQ_SW_SHBD_ALL_ADD,SQ_SW_SHBD_ALL_REMOV) VALUES ('2','לפי ני"ע','0','1','0','0','0','0');
INSERT INTO SQST_SUG_CHATACH (SQ_SUG_CHATACH,GL_TEUR,SQ_SW_HOVA_SCHUM,SQ_SW_SHBD_NOCH_REMO,SQ_SW_SHBD_ATIDI_ADD,SQ_SW_SHBD_ATIDI_REM,SQ_SW_SHBD_ALL_ADD,SQ_SW_SHBD_ALL_REMOV) VALUES ('3','לפי חתך','0','1','1','1','1','1');
INSERT INTO SQST_SUG_CHATACH (SQ_SUG_CHATACH,GL_TEUR,SQ_SW_HOVA_SCHUM,SQ_SW_SHBD_NOCH_REMO,SQ_SW_SHBD_ATIDI_ADD,SQ_SW_SHBD_ATIDI_REM,SQ_SW_SHBD_ALL_ADD,SQ_SW_SHBD_ALL_REMOV) VALUES ('4','לפי סכום','1','0','0','0','0','0');
COMMIT;



UPDATE mataf.BTT_VERSION_SUPPORT SET  VERSION = '5.28.08' WHERE VERSION = '5.28.07';
COMMIT;