--G.w.
--\App2\HamchaotMeutadotServer Talmor
CREATE ALIAS "MATAF"."HMST_SUG_HAFKADA"
  FOR "MATAF"."CHST_SUG_HAFKADA";


-- GLST_SGIA_MISHNI add new record - START
INSERT INTO GLST_SGIA_MISHNI (GL_ZIHUY_HODAA, GL_HODAA, GL_MIVNE_HALON_HODAA, GL_HUMRA_HODAA, GL_KOD_TIPUL) VALUES ('HM1001', 'בהזנת חשבון חותם יש להזין בנק וסניף חותם', 'MS', 'S', 'D');
COMMIT;

-- GLST_SGIA_MISHNI add new record - END

-- GLST_YEME_ASAKIM - tavla meshuderet - START
CREATE TABLE "MATAF"."GLST_YEME_ASAKIM" (
  "GL_TR_YYYYMMDD"			VARCHAR(8)	NOT NULL,
  "GL_YYYYMMDD_ASAKIM"		VARCHAR(8)	NOT NULL,
  "GL_YYYMMDD_ASKM_NEXT"	VARCHAR(8)	NOT NULL,
  "GL_SUG_YOM_ASAKIM"  		VARCHAR(1)	NOT NULL
) 
  IN "SNIFITZ";

ALTER TABLE "MATAF"."GLST_YEME_ASAKIM"
  ADD CONSTRAINT "GLST_YEME_ASAKIM_PK" PRIMARY KEY
    ("GL_TR_YYYYMMDD");

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "MATAF"."GLST_YEME_ASAKIM" TO USER "MATAFAPP";
-- GLST_YEME_ASAKIM - tavla meshuderet - END


--End \App2\HamchaotMeutadotServer Talmor


-- <IditG>, <IditG MP dbchanges - add message MP1003 to GLST_SGIA_MISHNI for 5.28.21>, 5/02/2012>
INSERT INTO GLST_SGIA_MISHNI (GL_ZIHUY_HODAA,GL_HODAA,GL_MIVNE_HALON_HODAA,GL_HUMRA_HODAA,GL_KOD_TIPUL)
VALUES('MP1003','יציאה מהעסקה ללא שמירה/שידור, הפעולה הגיעה מעסקה כספית דרוש אישור מנהל','MS','S','S');
COMMIT;


UPDATE mataf.BTT_VERSION_SUPPORT SET  VERSION = '5.28.20' WHERE VERSION = '5.28.10';
COMMIT;