--G.w.
SELECT * FROM mataf.BTT_VERSION_SUPPORT;
UPDATE mataf.BTT_VERSION_SUPPORT SET  VERSION = '5.28.06' WHERE VERSION = '5.28.05';
COMMIT;
-- UPDATE matafFFF.BTT_VERSION_SUPPORT SET  VERSION = '5.28.06' WHERE VERSION = '5.28.05';
SELECT COUNT(*) FROM mataf.BTT_VERSION_SUPPORT;