
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "A05S303EImpl", targetNamespace = "http://a05s303e")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface A05S303EImpl {


    /**
     * 
     * @param arg
     * @return
     *     returns client.A05C303DSADOT
     */
    @WebMethod
    @WebResult(name = "runReturn", targetNamespace = "")
    @RequestWrapper(localName = "run", targetNamespace = "http://a05s303e", className = "client.Run")
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://a05s303e", className = "client.RunResponse")
    public A05C303DSADOT run(
        @WebParam(name = "arg", targetNamespace = "")
        A05C303DSADOT arg);

}
