package oz.utils.autodeploy;

public enum AutoDeployOperations {
	DEPLOYEAR, EARWATCHER, SNIFITWATCHER, DEPLOYPORTAL, PORTALWATCHER, RIPPLESTARTCLUSTER, BACKUPCONFIG, EXITWATCHER, COPYLOADRULES, MODIFYLOADRULESCFG;
}
