--G.w.
SELECT * FROM mataf.BTT_VERSION_SUPPORT;
UPDATE mataf.BTT_VERSION_SUPPORT SET  VERSION = '5.28.06' WHERE VERSION = '5.28.05.05';
COMMIT;
UPDATE mataf.BTT_VERSION_SUPPORT SET  VERSION = '5.28.06' WHERE VERSION = '5.28.05.06';
SELECT * FROM  mataf.BTT_VERSION_SUPPORT;
SELECT COUNT(*) FROM  mataf.BTT_VERSION_SUPPORT;